export const OPPORTUNITY = "OPPORTUNITY";
export const LOGIN="LOGIN";
export const FASTTRACK="FASTTRACK";
export const NORMAL="NORMAL";
export const LOGOUT="LOGOUT";
export const CREATEASSESSEMENT="CREATEASSESSEMENT";
export const CLEANOPPORTUNITYDATA="CLEANOPPORTUNITYDATA";
export const CLEANCREATEASSESSEMENT="CLEANCREATEASSESSEMENT";
export const CLEANFASTTRACK="CLEANFASTTRACK"
 